export enum EnvVariables {
  APP_PORT = 'APP_PORT',
  APP_GLOBAL_PREFIX = 'APP_GLOBAL_PREFIX',
  AWS_S3_KEY = 'AWS_S3_KEY',
  AWS_S3_SECRET = 'AWS_S3_SECRET',
  AWS_S3_BUCKET = 'AWS_S3_BUCKET',
  AWS_S3_REGION = 'AWS_S3_REGION',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}
